version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7-stretch
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - run: bundle exec rspec
